name: M3u Fetch And Modify
on: 
  schedule: 
    - cron: 26 * * * *
  workflow_dispatch:
  repository_dispatch: #允许外部触发,cf worker定时任务延迟在1分钟以内
    types: [tvcron]
jobs:
  main:
    name: Fetch And Modify
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 允许推送代码
    #env:
    #  ONLY_UPDATE_MIGU: false    # 在这里修改：true 表示只更新 migu_merged.m3u，false 表示更新所有文件
    steps: 

    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Dependencies
      run: pip install requests
      
    - name: Set Environment
      run: |
        # 获取当前 UTC 小时
        CURRENT_HOUR=$(date -u +%H)
        
        # 如果是 09、21 点或者是手动触发，则为设置为 false
        if [[ "$CURRENT_HOUR" == "09" || "$CURRENT_HOUR" == "21" || "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "ONLY_UPDATE_MIGU=false" >> $GITHUB_ENV
        else
          echo "ONLY_UPDATE_MIGU=true" >> $GITHUB_ENV
        fi
        
    # ---  Migu 处理---
    - name: Process Migu Files
      continue-on-error: true     # 即使失败也会继续执行后续块 
      run: |
        python ./scripts/migu.py
        mv migu.txt mig.m3u
        python ./scripts/deduplicate.py -i mig.m3u -o mig_d.m3u
        python ./scripts/m3u_mergerng.py -i mig_d.m3u -o mig_d.m3u
        python ./scripts/m3u_merger.py -i mig_d.m3u -o mig_d.m3u
        
    # --- pluto&rakuten 源处理  ---
    - name: Process pluto&rakuten Files
      if: env.ONLY_UPDATE_MIGU != 'true'    
      continue-on-error: true
      run: |
            wget https://github.com/Afiq0/Pluto-TV-Playlists/raw/refs/heads/main/output/plutotv_us.m3u8 -O io.m3u  -t 2 --waitretry=5
            wget https://github.com/482349841209/rakuten-m3u-generator/raw/refs/heads/master/output/rakuten.m3u -O rkt.m3u  -t 2 --waitretry=5
            
    # --- hotel 源处理 ---
    - name: Process hotel Files
      if: false # env.ONLY_UPDATE_MIGU != 'true'    
      continue-on-error: true
      run: |
            wget http://120.27.21.75:20085/sub?biWVtPA3=txt -O htl.txt  -t 2 --waitretry=5 -T 30
            node ./scripts/txt2m3u.js -i htl.txt -o htl.m3u
            python ./scripts/m3u_purifier.py -i htl.m3u -n -mt 10
            python ./scripts/m3u_merger.py -i htl.m3u -o htl_merged.m3u
            python ./scripts/url_sortergr.py -i htl_merged.m3u -o htl_merged.m3u -gr '央视,卫视,其他' -gs  
            

    # --- hotel 源处理 2 ---
    - name: Process hotel Files 2
      if: false # env.ONLY_UPDATE_MIGU != 'true'    
      continue-on-error: true
      run: |
            wget https://github.com/zhlshrimp/Hotel_m3u/raw/refs/heads/main/lt.txt -O hlt.txt -t 2 --waitretry=5
            node ./scripts/txt2m3u.js -i hlt.txt -o hlt.m3u
            python ./scripts/extract.py --input hlt.m3u --output hlt.m3u --eoru '卫视高清,?' -n -r
            python ./scripts/m3u_purifier.py -i hlt.m3u -n -mt 10
            python ./scripts/m3u_merger.py -i hlt.m3u -o hlt_merged.m3u
            python ./scripts/url_sortergr.py -i hlt_merged.m3u -o hlt_merged.m3u -gr '央视,卫视,其他' -gs  
            
            wget https://github.com/zhlshrimp/Hotel_m3u/raw/refs/heads/main/dx.txt -O hdx.txt -t 2 --waitretry=5
            node ./scripts/txt2m3u.js -i hdx.txt -o hdx.m3u
            python ./scripts/m3u_purifier.py -i hdx.m3u -n -mt 10
            python ./scripts/m3u_merger.py -i hdx.m3u -o hdx_merged.m3u

            wget https://github.com/zhlshrimp/Hotel_m3u/raw/refs/heads/main/yd.txt -O hyd.txt -t 2 --waitretry=5
            node ./scripts/txt2m3u.js -i hyd.txt -o hyd.m3u
            python ./scripts/m3u_purifier.py -i hyd.m3u -n -mt 10
            python ./scripts/m3u_merger.py -i hyd.m3u -o hyd_merged.m3u

    # ---  提交推送 (这个步骤不建议加 continue-on-error，因为它是最终目标) ---
    - name: CommitAndPush
      run: |
        REPO_NAME="${GITHUB_REPOSITORY#*/}"
        git config --global user.email "github@github.com"
        git config --global user.name "Github Actions"
        
        git clone "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        cd "$REPO_NAME" || exit 1 

        # 使用 [ -f ] 检查文件是否存在再移动，防止因前面某块失败导致文件缺失而报错退出
        [ -f ../mig_d.m3u ] && mv ../mig_d.m3u ./migu.m3u || echo "migu skip"
        
        if [ "$ONLY_UPDATE_MIGU" != "true" ]; then
          
          [ -f ../htl.m3u ] && mv ../htl.m3u ./httop.m3u || true
          [ -f ../htl_merged.m3u ] && mv ../htl_merged.m3u ./httop_merged.m3u || true 
          [ -f ../hlt_merged.m3u ] && mv ../hlt_merged.m3u ./htllt_merged.m3u || true   
          [ -f ../hdx_merged.m3u ] && mv ../hdx_merged.m3u ./htldx_merged.m3u || true  
          [ -f ../hyd_merged.m3u ] && mv ../hyd_merged.m3u ./htlyd_merged.m3u || true            
          [ -f ../io.m3u ] && mv ../io.m3u ./plutotv.m3u || true
          [ -f ../rkt.m3u ] && mv ../rkt.m3u ./rakutentv.m3u || true
        fi

        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update: $(date +'%Y-%m-%d %H:%M:%S') UTC"
          git push origin main
        fi
