name: M3u Fetch And Modify
on: 
  schedule: 
    - cron: 10 * * * *
  workflow_dispatch:
  repository_dispatch: #允许外部触发,cf worker定时任务延迟在1分钟以内
    types: [tvcron]
jobs:
  main:
    name: Fetch And Modify
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 允许推送代码
    env:
      ONLY_UPDATE_MIGU: false    # 在这里修改：true 表示只更新 migu_merged.m3u，false 表示更新所有文件
    steps: 

    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Dependencies
      run: pip install requests
  
    # ---  Migu 处理---
    - name: Process Migu Files
      continue-on-error: true     # 即使失败也会继续执行后续块 
      run: |
        python ./scripts/migu.py
        python ./scripts/deduplicate.py -i mig.m3u -o mig_d.m3u
        python ./scripts/m3u_mergerng.py -i mig_d.m3u -o mig_d.m3u
        python ./scripts/m3u_merger.py -i mig_d.m3u -o mig_d.m3u
        
    # --- pluto&rakuten 源处理  ---
    - name: Process pluto&rakuten Files
      if: env.ONLY_UPDATE_MIGU != 'true'    
      continue-on-error: true
      run: |
        wget https://github.com/Afiq0/Pluto-TV-Playlists/raw/refs/heads/main/output/plutotv_us.m3u8 -O plt.m3u  -t 2 --waitretry=5
        wget https://github.com/482349841209/rakuten-m3u-generator/raw/refs/heads/master/output/rakuten.m3u -O rkt.m3u  -t 2 --waitretry=5

    # ---  提交推送 (这个步骤不建议加 continue-on-error，因为它是最终目标) ---
    - name: CommitAndPush
      run: |
        REPO_NAME="${GITHUB_REPOSITORY#*/}"
        git config --global user.email "github@github.com"
        git config --global user.name "Github Actions"
        
        git clone "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        cd "$REPO_NAME" || exit 1 

        # 使用 [ -f ] 检查文件是否存在再移动，防止因前面某块失败导致文件缺失而报错退出
        [ -f ../mig_d.m3u ] && mv ../mig_d.m3u ./migu.m3u || echo "migu skip"
        
        if [ "$ONLY_UPDATE_MIGU" != "true" ]; then
          [ -f ../plt.m3u ] && mv ../plt.m3u ./plutotv.m3u || true
          [ -f ../rkt.m3u ] && mv ../rkt.m3u ./rakutentv.m3u || true
        fi

        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update: $(date +'%Y-%m-%d %H:%M:%S') UTC"
          git push origin main
        fi
